/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.List;
import javax.swing.JTable;
import models.Personaje;

/**
 *
 * @author eduardo
 */
public class BattleField extends javax.swing.JFrame {

    private List<Personaje> equipo1;
    private List<Personaje> equipo2;
    
    public BattleField(List<Personaje> equipo1,List<Personaje> equipo2) {
        initComponents();
        lbGuillotina.setVisible(false);
        
        
        this.equipo1=equipo1;
        this.equipo2=equipo2;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonajesEquipo2 = new javax.swing.JTable() {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            public Class getColumnClass(int column)
            {
                return getValueAt(0, column).getClass();
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPersonajesEquipo1 = new javax.swing.JTable() {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            public Class getColumnClass(int column)
            {
                return getValueAt(0, column).getClass();
            }
        };
        inicio = new javax.swing.JLabel();
        lbHeal = new javax.swing.JLabel();
        lbGuillotina = new javax.swing.JLabel();
        lbAtk = new javax.swing.JLabel();
        lbImg2 = new javax.swing.JLabel();
        lbImg1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInfo = new javax.swing.JTable() {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            public Class getColumnClass(int column)
            {
                return getValueAt(0, column).getClass();
            }
        };
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campo de Batalla");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/logo.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 51));
        jScrollPane1.setOpaque(false);

        tablaPersonajesEquipo2.setBackground(new java.awt.Color(255, 153, 102));
        tablaPersonajesEquipo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaPersonajesEquipo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Personajes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonajesEquipo2.setToolTipText("Seleccione un personaje, y presione DELETE para eliminar");
        tablaPersonajesEquipo2.setOpaque(false);
        tablaPersonajesEquipo2.setRowHeight(130);
        tablaPersonajesEquipo2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablaPersonajesEquipo2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 130, 580));

        jScrollPane2.setBackground(new java.awt.Color(255, 102, 51));
        jScrollPane2.setOpaque(false);

        tablaPersonajesEquipo1.setBackground(new java.awt.Color(255, 153, 102));
        tablaPersonajesEquipo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaPersonajesEquipo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Personajes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonajesEquipo1.setToolTipText("Seleccione un personaje, y presione DELETE para eliminar");
        tablaPersonajesEquipo1.setOpaque(false);
        tablaPersonajesEquipo1.setRowHeight(130);
        tablaPersonajesEquipo1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tablaPersonajesEquipo1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 580));

        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/logo.png"))); // NOI18N
        inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 100, 110));

        lbHeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/heal.png"))); // NOI18N
        getContentPane().add(lbHeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, 70));

        lbGuillotina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/guillotine.png"))); // NOI18N
        getContentPane().add(lbGuillotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, 70));

        lbAtk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/attack.jpg"))); // NOI18N
        getContentPane().add(lbAtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 70));

        lbImg2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/characters/aldeano.jpg"))); // NOI18N
        getContentPane().add(lbImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 130, 170));

        lbImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/characters/aldeano.jpg"))); // NOI18N
        getContentPane().add(lbImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 130, 170));

        jScrollPane3.setBackground(new java.awt.Color(255, 102, 51));
        jScrollPane3.setOpaque(false);

        tablaInfo.setBackground(new java.awt.Color(255, 153, 102));
        tablaInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ataque", "Vida", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInfo.setToolTipText("Seleccione un personaje, y presione DELETE para eliminar");
        tablaInfo.setOpaque(false);
        tablaInfo.setRowHeight(130);
        tablaInfo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tablaInfo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 510, 110));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleField(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel inicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbAtk;
    private javax.swing.JLabel lbGuillotina;
    private javax.swing.JLabel lbHeal;
    private javax.swing.JLabel lbImg1;
    private javax.swing.JLabel lbImg2;
    private javax.swing.JTable tablaInfo;
    private javax.swing.JTable tablaPersonajesEquipo1;
    private javax.swing.JTable tablaPersonajesEquipo2;
    // End of variables declaration//GEN-END:variables
}
