/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.*;
import utilities.Audio;

/**
 *
 * @author eduardo
 */
public class Lobby extends javax.swing.JFrame {

    DefaultTableModel modeloTabla1;
    List<Personaje> listaPersonajesEquipo1 = new ArrayList<>();
    private int contadorPersonajesEquipo1 = 6;

    DefaultTableModel modeloTabla2;
    List<Personaje> listaPersonajesEquipo2 = new ArrayList<>();
    private int contadorPersonajesEquipo2 = 6;

    public Lobby(String nombreUsuario) {
        initComponents();

        modeloTabla1 = (DefaultTableModel) tablaPersonajesEquipo1.getModel();
        modeloTabla2 = (DefaultTableModel) tablaPersonajesEquipo2.getModel();

        /*
         banner.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/banner.jpg"))
         .getImage().getScaledInstance(banner.getWidth(), banner.getHeight(), Image.SCALE_DEFAULT)
         ));
         */
        this.setTitle("Usuario: " + nombreUsuario);
        this.setLocationRelativeTo(null);

        Thread hilo = new Thread() {
            @Override
            public void run() {
                try (BufferedReader br = new BufferedReader(
                        new FileReader(getClass().getResource("/resources/data/archivo.txt").toString())
                )) {
                    StringBuilder sb = new StringBuilder();
                    String line = br.readLine();

                    while (line != null) {
                        sb.append(line);
                        sb.append(System.lineSeparator());
                        line = br.readLine();
                    }
                    String everything = sb.toString();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Lobby.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Lobby.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox();
        lbImagen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btCrear = new javax.swing.JButton();
        tbpEq = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonajesEquipo1 = new javax.swing.JTable() {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            public Class getColumnClass(int column)
            {
                return getValueAt(0, column).getClass();
            }
        };
        jLabel3 = new javax.swing.JLabel();
        tfEq1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPersonajesEquipo2 = new javax.swing.JTable() {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            public Class getColumnClass(int column)
            {
                return getValueAt(0, column).getClass();
            }
        };
        jLabel5 = new javax.swing.JLabel();
        tfEq2 = new javax.swing.JTextField();
        btBatallar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/logo.png")).getImage()
        );
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setText("Nombre");

        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNombreKeyReleased(evt);
            }
        });

        jLabel2.setText("Rol");

        cbRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aldeano", "Mago", "Paladin" }));
        cbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRolActionPerformed(evt);
            }
        });

        lbImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/characters/aldeano.jpg"))); // NOI18N

        jLabel4.setText("Imagen");

        btCrear.setText("Crear");
        btCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCrearMouseClicked(evt);
            }
        });
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCrear)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(tfNombre)
                        .addComponent(cbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btCrear)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personaje", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 210, 350));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 51));
        jScrollPane1.setOpaque(false);

        tablaPersonajesEquipo1.setBackground(new java.awt.Color(255, 153, 102));
        tablaPersonajesEquipo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaPersonajesEquipo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ataque", "Vida", "Tipo", "Imagen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonajesEquipo1.setToolTipText("Seleccione un personaje, y presione DELETE para eliminar");
        tablaPersonajesEquipo1.setOpaque(false);
        tablaPersonajesEquipo1.setRowHeight(130);
        tablaPersonajesEquipo1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaPersonajesEquipo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaPersonajesEquipo1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPersonajesEquipo1);

        jLabel3.setText("Nombre de Equipo");

        tfEq1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEq1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(tfEq1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpEq.addTab("Equipo 1", jPanel2);

        jScrollPane2.setBackground(new java.awt.Color(255, 102, 51));
        jScrollPane2.setOpaque(false);

        tablaPersonajesEquipo2.setBackground(new java.awt.Color(255, 153, 102));
        tablaPersonajesEquipo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaPersonajesEquipo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ataque", "Vida", "Tipo", "Imagen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonajesEquipo2.setToolTipText("Seleccione un personaje, y presione DELETE para eliminar");
        tablaPersonajesEquipo2.setOpaque(false);
        tablaPersonajesEquipo2.setRowHeight(130);
        tablaPersonajesEquipo2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaPersonajesEquipo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaPersonajesEquipo2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPersonajesEquipo2);

        jLabel5.setText("Nombre de Equipo");

        tfEq2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEq2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(tfEq2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpEq.addTab("Equipo 2", jPanel4);

        getContentPane().add(tbpEq, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 460, 570));

        btBatallar.setText("LISTO PARA LA BATALA!!");
        btBatallar.setEnabled(false);
        btBatallar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatallarActionPerformed(evt);
            }
        });
        getContentPane().add(btBatallar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 170, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRolActionPerformed

        switch ((String) cbRol.getSelectedItem()) {

            case "Aldeano":
                lbImagen.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/characters/aldeano.jpg")));
                break;
            case "Mago":
                lbImagen.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/characters/mago.jpg")));
                break;
            case "Paladin":
                lbImagen.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/characters/paladin.jpg")));
                break;
        }
    }//GEN-LAST:event_cbRolActionPerformed

    private boolean existName(List<Personaje> lista, String nombre) {

        for (Personaje personaje : lista) {
            if (personaje.getNombre().equals(nombre)) {
                return true;
            }
        }
        return false;
    }


    private void btCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCrearMouseClicked

        if (tbpEq.getSelectedIndex() == 0 && contadorPersonajesEquipo1 == 0
                || tbpEq.getSelectedIndex() == 1 && contadorPersonajesEquipo2 == 0) {
            JOptionPane.showMessageDialog(this,
                    "Ya posee el numero maximo de personajes creados en este equipo");
            return;
        }

        if (tfNombre.getText().equals("")) {
            tfNombre.requestFocus();
            return;
        }

        if ((tbpEq.getSelectedIndex() == 0 && existName(listaPersonajesEquipo1, tfNombre.getText()))
                || (tbpEq.getSelectedIndex() == 1 && existName(listaPersonajesEquipo2, tfNombre.getText()))) {
            JOptionPane.showMessageDialog(this,
                    "Ya posee un personaje creado con este nombre en este equipo");
            tfNombre.requestFocus();
            return;
        }

        Personaje p = null;
        String tipo = "";

        switch ((String) cbRol.getSelectedItem()) {
            case "Aldeano":
                p = new Aldeano(tfNombre.getText());
                tipo = "Aldeano";
                break;
            case "Mago":
                p = new Mago(tfNombre.getText());
                tipo = "Mago";
                break;
            case "Paladin":
                p = new Paladin(tfNombre.getText());
                tipo = "Paladin";
                break;
        }

        switch (tbpEq.getSelectedIndex()) {
            case 0:
                modeloTabla1.addRow(new Object[]{
                    p.getNombre(),
                    p.getPt_ataque(),
                    p.getPt_vida(),
                    tipo,
                    new javax.swing.ImageIcon(getClass().
                    getResource("/resources/characters/" + tipo.toLowerCase() + ".jpg"))
                });
                listaPersonajesEquipo1.add(p);
                contadorPersonajesEquipo1--;
                break;
            case 1:
                modeloTabla2.addRow(new Object[]{
                    p.getNombre(),
                    p.getPt_ataque(),
                    p.getPt_vida(),
                    tipo,
                    new javax.swing.ImageIcon(getClass().
                    getResource("/resources/characters/" + tipo.toLowerCase() + ".jpg"))
                });
                listaPersonajesEquipo2.add(p);
                contadorPersonajesEquipo2--;
                break;
        }

        tfNombre.setText("");

        btBatallar.setEnabled(listaPersonajesEquipo1.size() >= 1 && listaPersonajesEquipo2.size() >= 1);

    }//GEN-LAST:event_btCrearMouseClicked

    private void tablaPersonajesEquipo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaPersonajesEquipo1KeyReleased
        if (tablaPersonajesEquipo1.getSelectedRow() == -1) {
            return;
        }

        int fila = tablaPersonajesEquipo1.getSelectedRow();

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            modeloTabla1.removeRow(fila);
            listaPersonajesEquipo1.remove(fila);
            contadorPersonajesEquipo1++;
            btBatallar.setEnabled(listaPersonajesEquipo1.size() >= 1 && listaPersonajesEquipo2.size() >= 1);
        }


    }//GEN-LAST:event_tablaPersonajesEquipo1KeyReleased

    private void tfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btCrearMouseClicked(null);
        }
    }//GEN-LAST:event_tfNombreKeyReleased

    private void tfEq1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEq1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEq1KeyReleased

    private void tablaPersonajesEquipo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaPersonajesEquipo2KeyReleased
        if (tablaPersonajesEquipo2.getSelectedRow() == -1) {
            return;
        }

        int fila = tablaPersonajesEquipo2.getSelectedRow();

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            modeloTabla2.removeRow(fila);
            listaPersonajesEquipo2.remove(fila);
            contadorPersonajesEquipo2++;
            btBatallar.setEnabled(listaPersonajesEquipo1.size() >= 1 && listaPersonajesEquipo2.size() >= 1);
        }

    }//GEN-LAST:event_tablaPersonajesEquipo2KeyReleased

    private void tfEq2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEq2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEq2KeyReleased

    private void btBatallarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatallarActionPerformed
        if (tfEq1.getText().equals("")) {
            tbpEq.setSelectedIndex(0);
            tfEq1.requestFocus();
            return;
        }

        if (tfEq2.getText().equals("")) {
            tbpEq.setSelectedIndex(1);
            tfEq2.requestFocus();
            return;
        }

        if (tfEq1.getText().equals(tfEq2.getText())) {
            JOptionPane.showMessageDialog(this,
                    "Los nombres de equipo no pueden ser iguales");
            return;
        }

        Audio atk = new Audio(getClass().getResource("/resources/sounds/attack.wav"));
        atk.play();

        Principal.backGroundSound.stop();
        //Principal.backGroundSound = new Audio(getClass().getResource("/resources/sounds/pelea.wav"));
        //Principal.backGroundSound.loop();

        dispose();
        new BattleField(listaPersonajesEquipo1, tfEq1.getText(), listaPersonajesEquipo2, tfEq2.getText()).setVisible(true);
    }//GEN-LAST:event_btBatallarActionPerformed

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btBatallar;
    private javax.swing.JButton btCrear;
    private javax.swing.JComboBox cbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JTable tablaPersonajesEquipo1;
    private javax.swing.JTable tablaPersonajesEquipo2;
    private javax.swing.JTabbedPane tbpEq;
    private javax.swing.JTextField tfEq1;
    private javax.swing.JTextField tfEq2;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
