/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.*;

/**
 *
 * @author eduardo
 */
public class Lobby extends javax.swing.JFrame {

    DefaultTableModel modelo;
    List<Personaje> listaPersonajes = new ArrayList<>();
    private int contadorPersonajes = 6;

    DefaultTableModel modelo1;
    List<Personaje> listaPersonajes1 = new ArrayList<>();
    private int contadorPersonajes1 = 6;

    public Lobby(String nombreUsuario) {
        initComponents();

        modelo = (DefaultTableModel) tablaPersonajes.getModel();
        modelo1 = (DefaultTableModel) tablaPersonajes1.getModel();

        /*
         banner.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/banner.jpg"))
         .getImage().getScaledInstance(banner.getWidth(), banner.getHeight(), Image.SCALE_DEFAULT)
         ));
         */
        this.setTitle("Usuario: " + nombreUsuario);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox();
        lbImagen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btCrear = new javax.swing.JButton();
        tbpEq = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonajes = new javax.swing.JTable() {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            public Class getColumnClass(int column)
            {
                return getValueAt(0, column).getClass();
            }
        };
        jLabel3 = new javax.swing.JLabel();
        tfEq1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPersonajes1 = new javax.swing.JTable() {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            public Class getColumnClass(int column)
            {
                return getValueAt(0, column).getClass();
            }
        };
        jLabel5 = new javax.swing.JLabel();
        tfEq2 = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/logo.png")).getImage()
        );
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setText("Nombre");

        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNombreKeyReleased(evt);
            }
        });

        jLabel2.setText("Rol");

        cbRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aldeano", "Mago", "Paladin" }));
        cbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRolActionPerformed(evt);
            }
        });

        lbImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/characters/aldeano.jpg"))); // NOI18N

        jLabel4.setText("Imagen");

        btCrear.setText("Crear");
        btCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCrear)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(tfNombre)
                        .addComponent(cbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btCrear)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personaje", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 210, 350));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 51));
        jScrollPane1.setOpaque(false);

        tablaPersonajes.setBackground(new java.awt.Color(255, 153, 102));
        tablaPersonajes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaPersonajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ataque", "Vida", "Tipo", "Imagen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonajes.setToolTipText("Seleccione un personaje, y presione DELETE para eliminar");
        tablaPersonajes.setOpaque(false);
        tablaPersonajes.setRowHeight(130);
        tablaPersonajes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaPersonajes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaPersonajesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPersonajes);

        jLabel3.setText("Nombre de Equipo");

        tfEq1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEq1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(tfEq1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpEq.addTab("Equipo 1", jPanel2);

        jScrollPane2.setBackground(new java.awt.Color(255, 102, 51));
        jScrollPane2.setOpaque(false);

        tablaPersonajes1.setBackground(new java.awt.Color(255, 153, 102));
        tablaPersonajes1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaPersonajes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ataque", "Vida", "Tipo", "Imagen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonajes1.setToolTipText("Seleccione un personaje, y presione DELETE para eliminar");
        tablaPersonajes1.setOpaque(false);
        tablaPersonajes1.setRowHeight(130);
        tablaPersonajes1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaPersonajes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaPersonajes1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPersonajes1);

        jLabel5.setText("Nombre de Equipo");

        tfEq2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEq2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(tfEq2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpEq.addTab("Equipo 2", jPanel4);

        getContentPane().add(tbpEq, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 460, 570));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRolActionPerformed

        switch ((String) cbRol.getSelectedItem()) {

            case "Aldeano":
                lbImagen.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/characters/aldeano.jpg")));
                break;
            case "Mago":
                lbImagen.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/characters/mago.jpg")));
                break;
            case "Paladin":
                lbImagen.setIcon(new javax.swing.ImageIcon(getClass()
                        .getResource("/resources/characters/paladin.jpg")));
                break;
        }
    }//GEN-LAST:event_cbRolActionPerformed

    private void btCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCrearMouseClicked

        if (tbpEq.getSelectedIndex() == 0 && contadorPersonajes == 0
                || tbpEq.getSelectedIndex() == 1 && contadorPersonajes1 == 0) {
            JOptionPane.showMessageDialog(this,
                    "Ya posee el numero maximo de personajes creados en este equipo");
            return;
        }

        if (tfNombre.getText().equals("")) {
            tfNombre.requestFocus();
            return;
        }

        Personaje p = null;
        String tipo = "";

        switch ((String) cbRol.getSelectedItem()) {
            case "Aldeano":
                p = new Aldeano(tfNombre.getText());
                tipo = "Aldeano";
                break;
            case "Mago":
                p = new Mago(tfNombre.getText());
                tipo = "Mago";
                break;
            case "Paladin":
                p = new Paladin(tfNombre.getText());
                tipo = "Paladin";
                break;
        }

        switch (tbpEq.getSelectedIndex()) {
            case 0:
                modelo.addRow(new Object[]{
                    p.getNombre(),
                    p.getPt_ataque(),
                    p.getPt_vida(),
                    tipo,
                    new javax.swing.ImageIcon(getClass().
                    getResource("/resources/characters/" + tipo.toLowerCase() + ".jpg"))
                });
                listaPersonajes.add(p);
                contadorPersonajes--;
                break;
            case 1:
                modelo1.addRow(new Object[]{
                    p.getNombre(),
                    p.getPt_ataque(),
                    p.getPt_vida(),
                    tipo,
                    new javax.swing.ImageIcon(getClass().
                    getResource("/resources/characters/" + tipo.toLowerCase() + ".jpg"))
                });
                listaPersonajes1.add(p);
                contadorPersonajes1--;
                break;
        }

        tfNombre.setText("");


    }//GEN-LAST:event_btCrearMouseClicked

    private void tablaPersonajesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaPersonajesKeyReleased
        if (tablaPersonajes.getSelectedRow() == -1) {
            return;
        }

        int fila = tablaPersonajes.getSelectedRow();

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            modelo.removeRow(fila);
            listaPersonajes.remove(fila);
            contadorPersonajes++;
        }


    }//GEN-LAST:event_tablaPersonajesKeyReleased

    private void tfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btCrearMouseClicked(null);
        }
    }//GEN-LAST:event_tfNombreKeyReleased

    private void tfEq1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEq1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEq1KeyReleased

    private void tablaPersonajes1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaPersonajes1KeyReleased
        if (tablaPersonajes1.getSelectedRow() == -1) {
            return;
        }

        int fila = tablaPersonajes1.getSelectedRow();

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            modelo1.removeRow(fila);
            listaPersonajes1.remove(fila);
            contadorPersonajes1++;
        }

    }//GEN-LAST:event_tablaPersonajes1KeyReleased

    private void tfEq2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEq2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEq2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btCrear;
    private javax.swing.JComboBox cbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JTable tablaPersonajes;
    private javax.swing.JTable tablaPersonajes1;
    private javax.swing.JTabbedPane tbpEq;
    private javax.swing.JTextField tfEq1;
    private javax.swing.JTextField tfEq2;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
